name: majidalbana
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4
  google_sign_in: ^6.2.2

  flutter_local_notifications: ^19.5.0

  video_thumbnail: ^0.5.3
  visibility_detector: ^0.4.0
  video_player: ^2.9.1
  share_plus: ^12.0.1
  app_links: ^6.4.0
  flutter_pdfview: ^1.3.2
  open_filex: ^4.7.0
  file_picker: ^10.3.2
  image_picker: ^1.1.2
  youtube_player_flutter: ^9.1.1
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.10.0
  path_provider: ^2.1.5
  http: ^1.2.2
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  pdf: ^3.12.0
  printing: ^5.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/iconwhite.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/jfflat.ttf
          weight: 400