// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_F4Ei6J_OnCbUCWANoH_wmDtU9UJJT9Y',
    appId: '1:14634099103:web:d8ddb22e3ce541d83d1daa',
    messagingSenderId: '14634099103',
    projectId: 'majidalbana-c2da3',
    authDomain: 'majidalbana-c2da3.firebaseapp.com',
    storageBucket: 'majidalbana-c2da3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMV2wujC4KKKTrVIiX45pO4EI25RlOdHY',
    appId: '1:14634099103:android:884c0d2554674fe63d1daa',
    messagingSenderId: '14634099103',
    projectId: 'majidalbana-c2da3',
    storageBucket: 'majidalbana-c2da3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACkgCBefJvqkkZh56fyw78PyQItqeF6fw',
    appId: '1:14634099103:ios:67e4f078bed0395f3d1daa',
    messagingSenderId: '14634099103',
    projectId: 'majidalbana-c2da3',
    storageBucket: 'majidalbana-c2da3.firebasestorage.app',
    androidClientId: '14634099103-jopb3156ul3kgfhihahc56lg1rsvt5lq.apps.googleusercontent.com',
    iosClientId: '14634099103-n5r847gqsgga7hdghhbvblpqg2tnjkc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.majidalbana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACkgCBefJvqkkZh56fyw78PyQItqeF6fw',
    appId: '1:14634099103:ios:67e4f078bed0395f3d1daa',
    messagingSenderId: '14634099103',
    projectId: 'majidalbana-c2da3',
    storageBucket: 'majidalbana-c2da3.firebasestorage.app',
    androidClientId: '14634099103-jopb3156ul3kgfhihahc56lg1rsvt5lq.apps.googleusercontent.com',
    iosClientId: '14634099103-n5r847gqsgga7hdghhbvblpqg2tnjkc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.majidalbana',
  );
}
